package com.poli.sh.model;
// Generated 23/06/2018 17:57:38 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Visitante generated by hbm2java
 */
@Entity
@Table(name = "visitante", catalog = "safehouse")
public class Visitante implements java.io.Serializable
{

    private static final long serialVersionUID = 4834274412977623142L;

    private Integer id;
    @JsonBackReference(value = "agen_visit")
    private AgendamentoVisita agendamentoVisita;
    private String nome;

    public Visitante()
    {
    }

    public Visitante(AgendamentoVisita agendamentoVisita, String nome)
    {
        this.agendamentoVisita = agendamentoVisita;
        this.nome = nome;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_agendamento_visita", nullable = false)
    public AgendamentoVisita getAgendamentoVisita()
    {
        return this.agendamentoVisita;
    }

    public void setAgendamentoVisita(AgendamentoVisita agendamentoVisita)
    {
        this.agendamentoVisita = agendamentoVisita;
    }

    @Column(name = "nome", nullable = false)
    public String getNome()
    {
        return this.nome;
    }

    public void setNome(String nome)
    {
        this.nome = nome;
    }

}
